ALTER TABLE "User"
ADD COLUMN "lastActiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Message"
ADD COLUMN "isSeen" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "seenAt" TIMESTAMP(3),
ADD COLUMN "archivedBySender" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "archivedByReceiver" BOOLEAN NOT NULL DEFAULT false;
